### ISSUE TITLE
how do i use this program?

### ISSUE THREAD

**Issue by murilopime** [Ravbug/GameGoogleTranslate#1]
I've been trying to use the program for days

**Comment by Ravbug** [comment]
What specifically are you trying to do?

**Comment by murilopime** [comment]
trying to use to translate minecraft several times

**Comment by Ravbug** [comment]
The way you do that with this tool is a little bit complicated. 
If you have a macOS device, you can run the [HyperTranslate](https://github.com/Ravbug/GameGoogleTranslate#hypertranslate) program which performs the translations offline (though you need an internet connection for it to download the models). If not, you can use the Splitter programs to take the game's `en_us.json` and convert it to a TSV file to paste into a google spreadsheet that calls `GOOGLETRANSLATE` repeatedly. 

I never really intended for people to use this project though, which is why it's lacking in documentation.

**Comment by murilopime** [comment]
how do i do that?

**Comment by murilopime** [comment]
never used google spreadsheet

**Comment by Ravbug** [comment]
You can take a look at this: https://support.google.com/docs/answer/3093331?hl=en

**Comment by murilopime** [comment]
OK thank you
